[BCM] set brcmpcmsink low_latency property for webrtc streams
Metrological/WebKitForWayland pull request #1011
Opened 2023-01-19 02:27 UTC by goruklu

Signed-off-by: Gurdal Oruklu <gurdal_oruklu@comcast.com>

2023-01-20 16:53 UTC, modeveci approved these changes
Looks good to me. @eocanha it is a platform specific change. can you also look at that?

2023-01-23 17:59 UTC, eocanha requested changes
Appart from the provided comments, everything looks fine.

2023-01-23 17:59 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +        if (player->m_streamPrivate != nullptr && g_object_class_find_property(G_OBJECT_GET_CLASS(element), "low_latency")) {
This code is inside a class member function, where you can directly use `m_streamPrivate` (no need for `player->`). In any case, the `player` variable wasn't defined, so this line shouldn't compile without the suggested correction.
Take advantage of this change to also remove `!= nullptr` and simply use `m_streamPrivate`. On C++ that's enough for not null checking.

2023-01-23 17:59 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +            g_object_set (G_OBJECT(element), "low_latency", TRUE, nullptr);
If you feel like and also think that this makes things simple, you can set the two properties at the same time with a single `g_object_set(object, "property1", value1, "property2", value2, ..., nullptr)` call. Do it or not at your own discretion.

2023-01-23 18:03 UTC, eocanha approved these changes
After a second read, the PR is fine enough to be squashed and merged.

2023-01-23 18:04 UTC, merged