Add a provision in WebKitURIResponse to check if the response is from a main frame resource
Metrological/WebKitForWayland pull request #1014
Opened 2023-01-23 08:56 UTC by varumugam123

2023-01-27 11:58 UTC, varumugam123 commented on Source/WebKit/Shared/API/glib/WebKitURIResponse.cpp
> +    g_object_class_install_property(
This property spec is incorrect, will update the PR

2023-01-27 12:35 UTC, varumugam123 commented
@magomez @modeveci Could you review the change?

2023-02-07 17:06 UTC, magomez requested changes

2023-02-07 17:06 UTC, magomez commented on Source/WebKit/Shared/API/glib/WebKitURIResponse.cpp
> +    RefPtr<API::NavigationResponse> navigationResponse;
You can just store a boolean instead of the NavigationResponse. Something like isMainFrame.

2023-02-07 17:06 UTC, magomez commented on Source/WebKit/Shared/API/glib/WebKitURIResponse.cpp
> +
You can pass a boolean here instead of the NavigationResponse. And call the function something like webkitURIResponseSetIsMainFrame().
There's no need to extend the life cycle of the NavigationResponse when all you want to know is whether it came from the main frame or not.

2023-02-07 17:06 UTC, magomez commented on Source/WebKit/Shared/API/glib/WebKitURIResponsePrivate.h
> +void webkitURIResponseSetNavigationResponse(WebKitURIResponse* response, RefPtr<API::NavigationResponse> navigationResponse);
Again, this should be updated to receive a boolean.

Also, for future patches: in order to share ownership, pointers are passed as raw pointers (inside the function a Ref or RefPtr is created for the pointer), which is what you want to do here. You should pass RefPtr only when you want to transfer ownership of the pointer, by declaring the parameter as RefPtr<type>&& and using WTFMove on the function invocation.

2023-02-07 17:06 UTC, magomez commented on Source/WebKit/UIProcess/API/glib/WebKitResponsePolicyDecision.cpp
> +    }
webkitURIResponseSetIsMainFrame(decision->priv->response.get(), decision->priv->navigationResponse->frame().isMainFrame());

2023-02-07 17:06 UTC, magomez commented on Source/WebKit/Shared/API/glib/WebKitURIResponse.cpp
> +    return response->priv->navigationResponse->frame().isMainFrame();
return response->priv->isMainFrame;

2023-02-08 10:33 UTC, varumugam123 commented on Source/WebKit/Shared/API/glib/WebKitURIResponse.cpp
> +
I agree on the comment, will update the PR

2023-02-08 10:33 UTC, varumugam123 commented on Source/WebKit/Shared/API/glib/WebKitURIResponsePrivate.h
> +void webkitURIResponseSetNavigationResponse(WebKitURIResponse* response, RefPtr<API::NavigationResponse> navigationResponse);
Noted the suggestion, Thanks for explaining.

2023-02-09 09:21 UTC, varumugam123 commented on Source/WebKit/Shared/API/glib/WebKitURIResponse.cpp
> +    RefPtr<API::NavigationResponse> navigationResponse;
Updated

2023-02-09 09:21 UTC, varumugam123 commented on Source/WebKit/Shared/API/glib/WebKitURIResponse.cpp
> +
Updated

2023-02-09 09:21 UTC, varumugam123 commented on Source/WebKit/Shared/API/glib/WebKitURIResponsePrivate.h
> +void webkitURIResponseSetNavigationResponse(WebKitURIResponse* response, RefPtr<API::NavigationResponse> navigationResponse);
Updated

2023-02-09 09:21 UTC, varumugam123 commented on Source/WebKit/UIProcess/API/glib/WebKitResponsePolicyDecision.cpp
> +    }
Updated

2023-02-09 09:21 UTC, varumugam123 commented on Source/WebKit/Shared/API/glib/WebKitURIResponse.cpp
> +    return response->priv->navigationResponse->frame().isMainFrame();
Updated

2023-02-09 10:30 UTC, magomez commented
Awesome! thanks @varumugam123

2023-02-09 10:30 UTC, merged