provision wal_autocheckpoint to prevent the log file growing to large size
Metrological/WebKitForWayland pull request #1045
Opened 2023-03-01 23:23 UTC by abstractmachines

This fix is ported from: 876e5e39e0f431b53d6924695dbdce927552bfd5 - PR 829 2.28

2023-03-01 23:40 UTC, abstractmachines commented
# Testing

In 2.28, set env var`WPE_WAL_AUTOCHECKPOINT` to a small number, launch cog browser, and increase localStorage while inspecting the `-wal` file growth, e.g. `root/.local/share/localstorage -wal` file(s);
- use remote web inspector and localStorage API, or browse localStorage-heavy site; env var set to a smaller value will result in `-wal` file on rpi3 being reset at more frequent intervals, and set to 0 bytes as expected with checkpoint TRUNCATE mode.

2.38 does checkpointing whenever rpi is booted - looking into this

2023-03-09 13:23 UTC, magomez requested changes

2023-03-09 13:23 UTC, magomez commented on Source/WebCore/platform/sql/SQLiteDatabase.cpp
> +    }
Couple of things here:
- you're reading the env var every time this function is called, something that's needed only once.
- you're not checking any error on atoi. It the value is not properly converted, we don't know what's returned (can be 0 or who knows).

I see something like this:
```
static constexpr int checkpointThresholdDefault = 1000;
static int checkpointThreshold = 0;

if (!checkpointThreshold) {
  auto envValue = String::fromLatin1(getenv("WPE_WAL_AUTOCHECKPOINT"));
  checkpointThreshold = parseInteger<int>(envValue).value_or(checkpointThresholdDefault);
}
```
which ensures that the env var is only read once the first time the function is called. If there's a valid env value, it's used, and if there's no value or it's invalid, then the default value is taken.

2023-03-09 13:59 UTC, magomez commented on Source/WebCore/platform/sql/SQLiteDatabase.cpp
> +    }
It would also be good to check that the content of the env var is not a negative value.

2023-03-09 17:34 UTC, abstractmachines commented on Source/WebCore/platform/sql/SQLiteDatabase.cpp
> +    }
Good call, I wasn't a fan of `atoi` either for same reasons; all changes made and tested fairly extensively. Thanks for the feedback!

2023-03-10 07:02 UTC, magomez approved these changes

2023-03-10 07:02 UTC, merged