[GStreamer] Do not send repeated encrypted events.
Metrological/WebKitForWayland pull request #508
Opened 2018-07-19 14:03 UTC by charlie-ht

This will break YouTube tests, since if they generateRequest twice with
the same init data, the request is rejected in WebKit, and will return
DOM exceptions during the tests.

2018-07-20 13:37 UTC, calvaris requested changes
Apart from the things I already commented, I suspect this creates decryption issues resulting in macroblocks.

2018-07-20 13:37 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/eme/WebKitCommonEncryptionDecryptorGStreamer.cpp
> +    WTF::HashSet<WebCore::InitData> m_processedEventData;
m_processedInitData

2018-07-20 13:37 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/eme/WebKitCommonEncryptionDecryptorGStreamer.cpp
> +            GST_TRACE_OBJECT(self, "event %u already handled", GST_EVENT_SEQNUM(event.get()));
This message is misleading, it should say something like "event %u init data already handled"

2018-07-20 13:38 UTC, calvaris commented
And more thorough testing, actually I would like to test them myself too.

2018-07-23 14:30 UTC, charlie-ht commented
I can't test this currently with playready on the YTTV Sintel asset, because of bugs in OCDM server. The widevine assert creates macroblocks because we don't have a valid keybox for decryption there.

2019-03-04 10:56 UTC, charlie-ht commented
Stale PR

2019-03-04 10:56 UTC, closed without merging