[EME][OCDM] Use the added userData in OCDM callbacks.
Metrological/WebKitForWayland pull request #595
Opened 2019-04-11 11:25 UTC by pawel-stanek-ml

The 2.22 pick of this will follow once this is settled.

2019-04-12 12:50 UTC, calvaris requested changes

2019-04-12 12:50 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp
> +HashSet<CDMInstanceOpenCDM::Session*> CDMInstanceOpenCDM::Session::m_sessionValidityTracker;
I think `m_validSessions` would be a better name.

For the current API, the arch is ok as it is. Now, I can ask Santa Klaus anything, I'd also ask for a _destroy notify_ function together with the user data. That way, OpenCDM would be in charge of finally destroying the user data. This would allow us to avoid this and use `WeakPtr`, though we would have to re-allocate it to the heap (no problem, `WeakPtr` has move constructor) and pass the pointer. Then it could be called as many times as necessary and if the main session object were destroyed, we would know it.

2019-04-12 12:50 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp
> +    Session* session = static_cast<Session*>(userData);
We'd better do a `reinterpret_cast` here

2019-04-12 12:50 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp
> +        // Went invalid in the meantime. It's possible due to leaping though the different threads.
If you ask me, I'd write "Became invalid" and "through".

2019-04-12 12:50 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp
> +void CDMInstanceOpenCDM::Session::openCDMNotification(Session* session, Notification method, RefPtr<SharedBuffer>&& buffer)
I think we can remove this function in favor of doing everything in the other one. If we are in the main thread at the bottom of the function we can just call the method and if we are not, we check the session validity in the lambda and if it is valid, we call the method. I think it would be easier.

2019-04-12 12:50 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp
> +    memset(&m_openCDMSessionCallbacks, 0, sizeof(m_openCDMSessionCallbacks));
You can probably initialize the variable with { } when it is declared without having to do this here.

2019-04-12 12:54 UTC, pawel-stanek-ml commented on Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp
> +    memset(&m_openCDMSessionCallbacks, 0, sizeof(m_openCDMSessionCallbacks));
Actually this rises a warning (at least in 2017 branch so GCC 5.X IINM) there's no initializators for all the fields on the list.

2019-04-15 07:02 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp
> +    memset(&m_openCDMSessionCallbacks, 0, sizeof(m_openCDMSessionCallbacks));
And can't we fix that rather than doing this?

2019-04-15 07:55 UTC, pawel-stanek-ml commented on Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp
> +    memset(&m_openCDMSessionCallbacks, 0, sizeof(m_openCDMSessionCallbacks));
by fixing you mean passing 6 nulls (because the new API added 3 new callbacks 3 of which will be later removed whan all the clients are adjusted) ?

2019-04-15 09:44 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp
> +    memset(&m_openCDMSessionCallbacks, 0, sizeof(m_openCDMSessionCallbacks));
Yes, six `nullptr`, yes.

2019-04-15 09:57 UTC, pawel-stanek-ml commented on Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp
> +    memset(&m_openCDMSessionCallbacks, 0, sizeof(m_openCDMSessionCallbacks));
It's seems there's a better solution which is simply { }. I've previously used { nullptr } which rises the warning.

2019-04-15 10:25 UTC, calvaris approved these changes

2019-04-15 15:44 UTC, merged