Remove BCM_NEXUS defines not needing gst changes
Metrological/WebKitForWayland pull request #615
Opened 2019-08-20 11:59 UTC by pawel-stanek-ml

This is a work I did towards removing BCM_NEXUS defines from Webkit and moving them to GST. It turned out not that many may be removed that way without changing the philosophy behind BRCM's plugins (vid/aud filter saying they accept all caps) but this is a part of it which allowed to remove some of the defines on Webkit side. There are still more which could be removed on Webkit side (asking GST factory about decoders vs parsers) but I didn't invest in them. The biggest one is to rely on generic query_position() without doing decoders lookup and jumping between them but this one requires GST change which is not yet official so I split this out.

2019-08-20 13:55 UTC, blino commented
See https://bugs.webkit.org/show_bug.cgi?id=197834 for an upstream fix of the MSE readyState, by @ybandou

2019-08-20 15:16 UTC, pawel-stanek-ml commented
> See https://bugs.webkit.org/show_bug.cgi?id=197834 for an upstream fix of the MSE readyState, by @ybandou

Oh. Thx. I didn't know it's fixed already upstream. I'll try to verify the upstream in my case and if it fixes problems from me I'll drop that commit from this PR.

2019-08-21 13:10 UTC, pawel-stanek-ml commented
> > See https://bugs.webkit.org/show_bug.cgi?id=197834 for an upstream fix of the MSE readyState, by @ybandou
> 
> Oh. Thx. I didn't know it's fixed already upstream. I'll try to verify the upstream in my case and if it fixes problems from me I'll drop that commit from this PR.

Nope. Doesn't fix the issue for me.

2019-08-21 15:49 UTC, eocanha requested changes
Thank you for submitting the pull request.

I've confirmed that http://qual-e.appspot.com/webaudio.html (the test that motivated the changes on https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/d53be79a6a8e3ab9d9a325ee0dc30cdc656a0169 that are modified by your patch) keeps working on Nexus after "Remove uneeded BCM_NEXUS from audiodestination", so I have nothing to object to that patch.

At first glance, I can't foresee any potential problem from the MSE buffering patch, so it's also ok for me.

Please find comments about the other patches in their respective commits.

2019-08-21 15:49 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp
> +GstElement* findElement(GstElement* element, ElementType type, MediaType media)
If you find it useful, this is a good moment to change the parameter name from "element" to something more meaningful such as "container". Same for getElement().

2019-08-21 15:49 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.h
> +GstElement* findElement(GstElement* element, ElementType type, MediaType media);
findElement() is now an auxiliar function of getElement(). If you don't foresee external code using findElement(), I'd just omit it from the header file and declare it inside an unnamed namespace (or static, at your choice) in GStreamerCommon.cpp.

2019-08-21 15:49 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp
> +bool matchesHints(const gchar* value, ElementType type, MediaType media)
Please, review all this algorithm. kElementTypeNameHints and kMediaTypeNameHints are both an array of 3 elements, each of them being an array of 3 strings that are uninitialized. Maybe you forgot to initialize them to some value? In my case, they are nullptr at runtime (that is, the first *elementHints and *mediaHints == nullptr), therefore the two while loops below never iterate and the whole function seems useless.

In my case, the whole thing works on Nexus (Arris) because m_videoSink has been initialized to an brcmvideosink instance and there's no need to use matchesHints() nor matchesType().

2019-08-21 15:49 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.h
> +    long long determineTotalBytes() const;
This method doesn't seem to be meant to be used from outside, so it should be private.

2019-08-21 15:49 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +        m_isStreaming = length >= 0 ? length == 0 : false;
This is equivalent to the previous "m_isStreaming = !length" condition.

2019-08-21 15:49 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +    m_isStreaming = length >= 0 ? length == 0 : false;
Same here.

2019-08-21 18:33 UTC, pawel-stanek-ml commented on Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp
> +bool matchesHints(const gchar* value, ElementType type, MediaType media)
Good catch. I indeed lost the initialization code somehow.

2019-08-22 11:33 UTC, eocanha commented
The new fixes are fine in terms of functionality. Now please pass the style checker (`Tools/Scripts/check-webkit-style -g f5c952a934c^..b03de54c453`), solve all the warnings, `git rebase -i wpe-2.22` reordering the fixup commits squashing them as fixup with their original counterparts, and the pull request is good to go from my side.

2019-08-22 11:37 UTC, pawel-stanek-ml commented
just FYI: OFC I was not going to push fixup commits but wanted for changes to be apparent. Now I'll do history rewrite one the style is fixed.

2019-08-22 12:16 UTC, pawel-stanek-ml commented
Style fixed. Once approved I'll rebase and merge

2019-08-22 13:39 UTC, merged