[EME][CDM] rename messageQueue to messageQueueFromCDM
Metrological/WebKitForWayland pull request #620
Opened 2019-09-13 21:52 UTC by goruklu

MediaKeySession::engqueueMessage(CDMInstanceClient::MessageType type, Ref<SharedBuffer>&& message)is  calling itself recursively instead of calling 
MediaKeySession::enqueueMessage(MediaKeyMessageType messageType, const SharedBuffer& message)

I think the prototype amount to the same thing. Renaming it to enqueueMessageFromCDM() solves the problem

```
void MediaKeySession::enqueueMessage(CDMInstanceClient::MessageType type, Ref<SharedBuffer>&& message)
{
    m_taskQueue.enqueueTask([this, type, message = WTFMove(message)] () mutable {
        MediaKeyMessageType messageType;
        switch (type) {
        case CDMInstance::MessageType::LicenseRequest:
            messageType = MediaKeyMessageType::LicenseRequest;
            break;
        case CDMInstance::MessageType::LicenseRenewal:
            messageType = MediaKeyMessageType::LicenseRenewal;
            break;
        case CDMInstance::MessageType::LicenseRelease:
            messageType = MediaKeyMessageType::LicenseRelease;
            break;
        case CDMInstance::MessageType::IndividualizationRequest:
            messageType = MediaKeyMessageType::IndividualizationRequest;
            break;
        }

        enqueueMessage(messageType, WTFMove(message));
    });
}
```

2019-09-14 04:46 UTC, pawel-stanek-ml requested changes
This was called onMessage() in the original code but got renamed during review and this case wasn't tested afterwards, it seems. Anyway. It's overload this is why compiler accepts it. The problem however is the first argument which looks different but it's the same thing. I do not like FromCDM part, though since it's redundant. I propose issueMessage() instead.

2019-09-14 04:49 UTC, pawel-stanek-ml commented
While on this please update commit message too (change messageQueue to enqueueMessage and drop info what it's renamed to but give the reason for doing so insteas)

2019-09-15 08:16 UTC, pawel-stanek-ml approved these changes

2019-09-15 09:54 UTC, merged

2019-09-16 17:28 UTC, calvaris commented
I should have reviewed this. A better name would have been `enqueueMessageWithTask`. Please fix it.