[GStreamer][EME] Condition 1.16 specific features out
Metrological/WebKitForWayland pull request #631
Opened 2019-10-11 13:10 UTC by charlie-ht

If you select one of 1.10 or 1.14 (options in the master buildroot), GST_PROTECTION_UNSPECIFIED_SYSTEM_ID does not exist and WebKit will fail to compile.

2019-10-11 13:20 UTC, pawel-stanek-ml requested changes
Actually we have the required patches downported to 1.10 (need them and use them with GST 1.10) so it's only GST 1.14 which won't compile. I'd also expect that in case we have to go with GST 1.14 before jumping to 1.16 it might be still required and nice to have encrypted webm working so a better approach would be to port them all there too.

2019-10-11 13:23 UTC, charlie-ht commented
@pawel-stanek-ml OK, I'm still getting caught up on the downstream status. I only tested with 1.14 and guessed about 1.10 :-)
I will look at porting these to 1.14, thanks for the review!

2019-10-11 13:33 UTC, pawel-stanek-ml commented
Likewise thank you! I had it on my TODO list due to the fact arris config uses gst 1.14 by default but hasn't manage to get to it, yet.

2019-10-14 19:56 UTC, charlie-ht commented
Closing because this is resolved by https://github.com/WebPlatformForEmbedded/buildroot/pull/137

2019-10-14 19:56 UTC, closed without merging