[GSTUTILS] getElement() leak fix.
Metrological/WebKitForWayland pull request #681
Opened 2020-10-20 17:02 UTC by pawel-stanek-ml

In one code path (gtting sinks from playbin) the caller is
responsible for freeing the returned element and on the other one
(findElement()) does not copy thus no free is needed. In order
to hide that and properly act no matter the path GRefPtr is now
returned from the function and for the case which does not copy
ref cnt is increased.

2020-10-21 09:43 UTC, calvaris commented
I am having trouble to understand what we're trying to fix there, I need a better explanation.

Anyway, this is not something to fix here, but upstream and then bringing it back down so I am closing this here until I see the bug upstream.

2020-10-21 09:48 UTC, pawel-stanek-ml commented
I do not think this code is in upstream, is it?
The fix here is that util's getElemet() returns an element the caller is responsible for freeing and even this was not consistent because one path required freeing but other one not. So this is now consistent - the caller needs to free - but on the same time it's made easy due to returning ref ptr..

2020-10-21 09:50 UTC, pawel-stanek-ml commented
This fixes leak which are there, essentially.

2020-10-21 10:56 UTC, eocanha commented
My understanding is that the caller (`decodedFrameCount()`) isn't responsible of freeing `GstElement* sink` in anyh of the two (actually three) codepaths (`GstElement* sink = m_fpsSink.get()`, `m_videoSink.get()` and `getElement(m_pipeline.get(), ElementType::SINK, MediaType::VIDEO)`).

In the m_fpsSink codepath, the m_fpsSink lifecycle is managed by the creation of the pipeline and the destruction of the pipeline (in ~MediaPlayerPrivateBase the attribute is automatically unreffed). No explicit unreffing is needed in `decodeFrameCount()`. The pointer must be treated as a constant pointer.

The m_videoSink case is similar to m_fpsSink. It's managed by the pipeline creation and MediaPlayerPrivateBase destruction. The pointer is constant for us, no unreffing needed.

In the `getElement()` codepath, the function returns the requested element with transfer-none (no need to free). At least in theory (more on that later, spoiler: it's false). This is the same case as for fpsSink, "at least in theory".

So, the conclusion is that there's nothing to worry about in `decodeFrameCount()`. Now let's have a look at `getElement()`:

The `g_object_get()` branches are transfer-full (ouch, this is a problem!). The `findElement()` branch is transfer-none, because the base case ([else branch](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp#L138)) just returns the container without altering the number of refs and the recursive/iterative case ([then branch](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp#L115)) uses `g_value_get_object()` to get the container, and [that method is transfer-none](https://developer.gnome.org/gobject/stable/gobject-Standard-Parameter-and-Value-Types.html#g-value-get-object).

So, the conclusion is that `g_object_get()`'s transfer-full problem must be solved. It can be solved in two ways: just unreffing the element after the call to `g_object_get()` (since we're sure that the sink will survive until playbin is destroyed), or migrating everything to GRefPtr, which is what you did.

Using `&ret.outPtr()` to pick the audio-sink/video-sink element was the right thing to do, since it guarantees that [no extra reference increase will happen when picking](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WTF/wtf/glib/GRefPtr.h#L95) (`g_object_get()` already does that for us, as it's transfer-full) and [an unref will happen when clearing GRefPtr](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WTF/wtf/glib/GRefPtr.h#L85).

The `findElement()` branch in `getElement()` is also technically fine, since you first ref a transfer-none element to transform it into a transfer-full one (own it) and then you assign it to ret using the same strategy as in the audio/video-sink case. If I can suggest an improvement, I would just do it by just assigning `ret = element`. That [will increase the refcount and assign the pointer in one step](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WTF/wtf/glib/GRefPtr.h#L150).

It's true that none of these functions exist upstream, so in my opinion this patch keeps being relevant as a merge request for this repository.

2020-10-21 11:03 UTC, eocanha requested changes

2020-10-21 11:03 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp
> +    GRefPtr<GstElement> ret;
Use a meaningul (full) name for this. I'd suggest `result`.

2020-10-21 11:03 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp
> +            ret.outPtr() = element;
Use just a single line with an assignment: `result = element`. This will increase the refcount and assign, which is what you want. Actually, the original line (`found = findElement()`) was doing exactly that. Leave it like that and just change the variable name to `result`.

2020-10-21 11:03 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp
> +    GRefPtr<GstElement> scopedSink;
Use just `GRefPtr<GstElement> sink` for everything, using `sink.get()` as needed in the rest of the code below to make it build in places where a `GstElement*` is needed.

2020-10-21 11:03 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp
> -        sink = m_videoSink ? m_videoSink.get() : getElement(m_pipeline.get(), ElementType::SINK, MediaType::VIDEO);
Now that sink will be a GRefPtr, keep the old line, removing the `.get()` for `m_videoSink` and keeping `getElement()`

2020-10-21 11:03 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp
>          g_object_get(sink, "frames-rendered", &decodedFrames, nullptr);
Now `sink.get()`

2020-10-21 11:06 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp
> +        g_object_ref(re);
Remove this. Let's leave `findElement()` as transfer-none, like before.

2020-10-21 16:50 UTC, pawel-stanek-ml commented
> My understanding is that the caller (`decodedFrameCount()`) isn't responsible of freeing `GstElement* sink` in anyh of the two (actually three) codepaths (`GstElement* sink = m_fpsSink.get()`, `m_videoSink.get()` and `getElement(m_pipeline.get(), ElementType::SINK, MediaType::VIDEO)`).
> 
> In the m_fpsSink codepath, the m_fpsSink lifecycle is managed by the creation of the pipeline and the destruction of the pipeline (in ~MediaPlayerPrivateBase the attribute is automatically unreffed). No explicit unreffing is needed in `decodeFrameCount()`. The pointer must be treated as a constant pointer.
> 
> The m_videoSink case is similar to m_fpsSink. It's managed by the pipeline creation and MediaPlayerPrivateBase destruction. The pointer is constant for us, no unreffing needed.
> 
> In the `getElement()` codepath, the function returns the requested element with transfer-none (no need to free). At least in theory (more on that later, spoiler: it's false). This is the same case as for fpsSink, "at least in theory".
> 
> So, the conclusion is that there's nothing to worry about in `decodeFrameCount()`. Now let's have a look at `getElement()`:
> 
> The `g_object_get()` branches are transfer-full (ouch, this is a problem!). The `findElement()` branch is transfer-none, because the base case ([else branch](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp#L138)) just returns the container without altering the number of refs and the recursive/iterative case ([then branch](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp#L115)) uses `g_value_get_object()` to get the container, and [that method is transfer-none](https://developer.gnome.org/gobject/stable/gobject-Standard-Parameter-and-Value-Types.html#g-value-get-object).
> 
> So, the conclusion is that `g_object_get()`'s transfer-full problem must be solved. It can be solved in two ways: just unreffing the element after the call to `g_object_get()` (since we're sure that the sink will survive until playbin is destroyed), or migrating everything to GRefPtr, which is what you did.
> 
> Using `&ret.outPtr()` to pick the audio-sink/video-sink element was the right thing to do, since it guarantees that [no extra reference increase will happen when picking](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WTF/wtf/glib/GRefPtr.h#L95) (`g_object_get()` already does that for us, as it's transfer-full) and [an unref will happen when clearing GRefPtr](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WTF/wtf/glib/GRefPtr.h#L85).
> 
> The `findElement()` branch in `getElement()` is also technically fine, since you first ref a transfer-none element to transform it into a transfer-full one (own it) and then you assign it to ret using the same strategy as in the audio/video-sink case. If I can suggest an improvement, I would just do it by just assigning `ret = element`. That [will increase the refcount and assign the pointer in one step](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WTF/wtf/glib/GRefPtr.h#L150).
> 
> It's true that none of these functions exist upstream, so in my opinion this patch keeps being relevant as a merge request for this repository.

Now we're on a same page indeed

2020-10-21 17:02 UTC, pawel-stanek-ml commented
> My understanding is that the caller (`decodedFrameCount()`) isn't responsible of freeing `GstElement* sink` in anyh of the two (actually three) codepaths (`GstElement* sink = m_fpsSink.get()`, `m_videoSink.get()` and `getElement(m_pipeline.get(), ElementType::SINK, MediaType::VIDEO)`).
> 
> In the m_fpsSink codepath, the m_fpsSink lifecycle is managed by the creation of the pipeline and the destruction of the pipeline (in ~MediaPlayerPrivateBase the attribute is automatically unreffed). No explicit unreffing is needed in `decodeFrameCount()`. The pointer must be treated as a constant pointer.
> 
> The m_videoSink case is similar to m_fpsSink. It's managed by the pipeline creation and MediaPlayerPrivateBase destruction. The pointer is constant for us, no unreffing needed.
> 
> In the `getElement()` codepath, the function returns the requested element with transfer-none (no need to free). At least in theory (more on that later, spoiler: it's false). This is the same case as for fpsSink, "at least in theory".
> 
> So, the conclusion is that there's nothing to worry about in `decodeFrameCount()`. Now let's have a look at `getElement()`:
> 
> The `g_object_get()` branches are transfer-full (ouch, this is a problem!). The `findElement()` branch is transfer-none, because the base case ([else branch](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp#L138)) just returns the container without altering the number of refs and the recursive/iterative case ([then branch](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp#L115)) uses `g_value_get_object()` to get the container, and [that method is transfer-none](https://developer.gnome.org/gobject/stable/gobject-Standard-Parameter-and-Value-Types.html#g-value-get-object).
> 
> So, the conclusion is that `g_object_get()`'s transfer-full problem must be solved. It can be solved in two ways: just unreffing the element after the call to `g_object_get()` (since we're sure that the sink will survive until playbin is destroyed), or migrating everything to GRefPtr, which is what you did.
> 
> Using `&ret.outPtr()` to pick the audio-sink/video-sink element was the right thing to do, since it guarantees that [no extra reference increase will happen when picking](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WTF/wtf/glib/GRefPtr.h#L95) (`g_object_get()` already does that for us, as it's transfer-full) and [an unref will happen when clearing GRefPtr](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WTF/wtf/glib/GRefPtr.h#L85).
> 
> The `findElement()` branch in `getElement()` is also technically fine, since you first ref a transfer-none element to transform it into a transfer-full one (own it) and then you assign it to ret using the same strategy as in the audio/video-sink case. If I can suggest an improvement, I would just do it by just assigning `ret = element`. That [will increase the refcount and assign the pointer in one step](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WTF/wtf/glib/GRefPtr.h#L150).
> 
> It's true that none of these functions exist upstream, so in my opinion this patch keeps being relevant as a merge request for this repository.

and a really nice improvement suggestion. Thanks. Makes things clearer

2020-10-21 17:33 UTC, eocanha requested changes
Remember to remove the extra g_object_ref(re) you added in findElement().

2020-10-21 18:01 UTC, pawel-stanek-ml commented
> Remember to remove the extra g_object_ref(re) you added in findElement().

it's no longer there

2020-10-21 18:03 UTC, pawel-stanek-ml commented
> > Remember to remove the extra g_object_ref(re) you added in findElement().
> 
> it's no longer there

it was there. My bad. Good catch

2020-10-21 18:20 UTC, merged

2020-10-21 18:22 UTC, eocanha commented
Argh! Forgot to squash the commits before merging. 🤦

2020-10-21 18:53 UTC, pawel-stanek-ml commented
Ah. It was the default for me. Should we leave it be or ... force...?

2020-10-22 09:43 UTC, eocanha commented
I tried to force-push but, in a wise decision by the repository administrators, the wpe-2.22 branch is protected against force-pushes:
```
remote: error: GH006: Protected branch update failed for refs/heads/wpe-2.22.
remote: error: Cannot force-push to this protected branch
```
The commits will have to remain unsquashed forever.